name: CI/CD with Sentry

on:
  push:
    branches:
      - main

jobs:
  sentry:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Configure Sentry environment variables and determine version
      run: |
        # Install the Sentry CLI
        curl -sL https://sentry.io/get-cli/ | bash
    
        # Setup configuration values
        SENTRY_AUTH_TOKEN=c5c6f1cec324d1ddc8b4fd7e1d447e728da714c2adf1e5e2d956896bdaf63940
        SENTRY_ORG=monitoreo-xochicalli
        SENTRY_PROJECT=xochicalli_monitoreo
        VERSION=$(sentry-cli releases propose-version)
        # Remove any invalid characters from the version
        VERSION=$(echo "$VERSION" | tr -cd '[:alnum:]._-')
        echo "Sentry release version: $VERSION"
    
    - name: Debug print VERSION
      run: echo "VERSION: $VERSION"
    
    - name: Create and finalize Sentry release
      run: |
        echo "Creating Sentry release for version $VERSION"
        sentry-cli releases new "$VERSION"
        sentry-cli releases set-commits "$VERSION" --auto
        sentry-cli releases finalize "$VERSION"
    