name: CI/CD with Sentry

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install  --force # O el comando necesario para instalar las dependencias de tu proyecto

    - name: Install Sentry CLI
      run: curl -sL https://sentry.io/get-cli/ | bash

    - name: Configure Sentry environment variables
      run: |
        export SENTRY_AUTH_TOKEN=c5c6f1cec324d1ddc8b4fd7e1d447e728da714c2adf1e5e2d956896bdaf63940
        export SENTRY_ORG=monitoreo-xochicalli
        export SENTRY_PROJECT=xochicalli_monitoreo
        export VERSION=$(sentry-cli releases propose-version)

    - name: Create and finalize Sentry release
      run: |
        sentry-cli releases new "$VERSION"
        sentry-cli releases set-commits "$VERSION" --auto
        sentry-cli releases finalize "$VERSION"
